[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DLILYGO_WATCH_2020_V3 -DDISABLE_DIAGNOSTIC_OUTPUT
lib_deps =
    lewisxhe/AXP202X_Library
    lewisxhe/SensorLib
    lvgl/lvgl@^7.7.2
    bodmer/TFT_eSPI

    adafruit/Adafruit BusIO
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    adafruit/Adafruit Unified Sensor
    Wire
    SPI
build_unflags = -Os
build_type = debug
