[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DLILYGO_WATCH_2020_V3 -DDISABLE_DIAGNOSTIC_OUTPUT
lib_deps =
    lewisxhe/AXP202X_Library
    lewisxhe/SensorLib
