; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = native

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DDISABLE_DIAGNOSTIC_OUTPUT
lib_deps = bodmer/TFT_eSPI@^2.5.43

[env:native]
platform = native
build_flags =
    -DNATIVE_BUILD
    -std=c++17
    -DDISABLE_DIAGNOSTIC_OUTPUT
test_build_src = false
test_filter = test_native, test_battery, test_statemachine, test_ble_audio
lib_deps = bodmer/TFT_eSPI@^2.5.43

[env:native_lvgl]
platform = native
build_flags =
    -DNATIVE_BUILD
    -std=c++17
    -DDISABLE_DIAGNOSTIC_OUTPUT
    -DLV_BUILD_TEST
    -DLV_CONF_INCLUDE_SIMPLE
    -Isrc/lvgl/src
    -Isrc/lvgl/..
    -Isrc
test_build_src = true
build_src_filter = +<lvgl/> -<lvgl/tests/>
test_filter = test_lvgl_render
lib_deps = bodmer/TFT_eSPI@^2.5.43
