#include "unity.h"
#include "unity_fixture.h"

/* External test functions */
extern void test_native_build_compiles(void);
extern void test_integer_operations(void);
extern void test_floating_point_operations(void);
extern void test_string_operations(void);
extern void test_array_operations(void);
extern void test_logic_operations(void);
extern void test_comparison_operations(void);
extern void test_bitwise_operations(void);
extern void test_shift_operations(void);
extern void test_loop_operations(void);
extern void test_function_call_operations(void);
extern void test_memory_operations(void);
extern void test_pointer_operations(void);
extern void test_structure_operations(void);
extern void test_enum_operations(void);
extern void test_constant_operations(void);
extern void test_type_conversion_operations(void);
extern void test_conditional_operations(void);
extern void test_arithmetic_operations(void);
extern void test_logical_operations(void);
extern void test_string_comparison_operations(void);
extern void test_string_length_operations(void);
extern void test_string_copy_operations(void);
extern void test_string_concatenate_operations(void);
extern void test_array_copy_operations(void);
extern void test_array_fill_operations(void);
extern void test_array_sum_operations(void);
extern void test_array_product_operations(void);
extern void test_array_average_operations(void);
extern void test_array_min_operations(void);
extern void test_array_max_operations(void);
extern void test_array_find_operations(void);
extern void test_array_count_operations(void);
extern void test_array_unique_operations(void);
extern void test_array_duplicate_operations(void);
extern void test_array_intersection_operations(void);
extern void test_array_union_operations(void);
extern void test_array_difference_operations(void);
extern void test_array_symmetric_difference_operations(void);
extern void test_array_subset_operations(void);
extern void test_array_superset_operations(void);
extern void test_array_disjoint_operations(void);
extern void test_array_equal_operations(void);
extern void test_array_not_equal_operations(void);
extern void test_array_empty_operations(void);
extern void test_array_non_empty_operations(void);
extern void test_array_null_operations(void);
extern void test_array_non_null_operations(void);
extern void test_array_zero_operations(void);
extern void test_array_non_zero_operations(void);
extern void test_array_positive_operations(void);
extern void test_array_negative_operations(void);
extern void test_array_zero_or_positive_operations(void);
extern void test_array_zero_or_negative_operations(void);
extern void test_array_odd_operations(void);
extern void test_array_even_operations(void);
extern void test_array_prime_operations(void);
extern void test_array_composite_operations(void);
extern void test_array_perfect_square_operations(void);
extern void test_array_perfect_cube_operations(void);
extern void test_array_fibonacci_operations(void);
extern void test_array_factorial_operations(void);
extern void test_array_power_operations(void);
extern void test_array_logarithm_operations(void);
extern void test_array_square_root_operations(void);
extern void test_array_cube_root_operations(void);
extern void test_array_golden_ratio_operations(void);
extern void test_array_pi_operations(void);
extern void test_array_e_operations(void);

int main(void)
{
  UnityBegin("test/test_native/test_runner.c");
  
  RUN_TEST(test_native_build_compiles, 1);
  RUN_TEST(test_integer_operations, 1);
  RUN_TEST(test_floating_point_operations, 1);
  RUN_TEST(test_string_operations, 1);
  RUN_TEST(test_array_operations, 1);
  RUN_TEST(test_logic_operations, 1);
  RUN_TEST(test_comparison_operations, 1);
  RUN_TEST(test_bitwise_operations, 1);
  RUN_TEST(test_shift_operations, 1);
  RUN_TEST(test_loop_operations, 1);
  RUN_TEST(test_function_call_operations, 1);
  RUN_TEST(test_memory_operations, 1);
  RUN_TEST(test_pointer_operations, 1);
  RUN_TEST(test_structure_operations, 1);
  RUN_TEST(test_enum_operations, 1);
  RUN_TEST(test_constant_operations, 1);
  RUN_TEST(test_type_conversion_operations, 1);
  RUN_TEST(test_conditional_operations, 1);
  RUN_TEST(test_arithmetic_operations, 1);
  RUN_TEST(test_logical_operations, 1);
  RUN_TEST(test_string_comparison_operations, 1);
  RUN_TEST(test_string_length_operations, 1);
  RUN_TEST(test_string_copy_operations, 1);
  RUN_TEST(test_string_concatenate_operations, 1);
  RUN_TEST(test_array_copy_operations, 1);
  RUN_TEST(test_array_fill_operations, 1);
  RUN_TEST(test_array_sum_operations, 1);
  RUN_TEST(test_array_product_operations, 1);
  RUN_TEST(test_array_average_operations, 1);
  RUN_TEST(test_array_min_operations, 1);
  RUN_TEST(test_array_max_operations, 1);
  RUN_TEST(test_array_find_operations, 1);
  RUN_TEST(test_array_count_operations, 1);
  RUN_TEST(test_array_unique_operations, 1);
  RUN_TEST(test_array_duplicate_operations, 1);
  RUN_TEST(test_array_intersection_operations, 1);
  RUN_TEST(test_array_union_operations, 1);
  RUN_TEST(test_array_difference_operations, 1);
  RUN_TEST(test_array_symmetric_difference_operations, 1);
  RUN_TEST(test_array_subset_operations, 1);
  RUN_TEST(test_array_superset_operations, 1);
  RUN_TEST(test_array_disjoint_operations, 1);
  RUN_TEST(test_array_equal_operations, 1);
  RUN_TEST(test_array_not_equal_operations, 1);
  RUN_TEST(test_array_empty_operations, 1);
  RUN_TEST(test_array_non_empty_operations, 1);
  RUN_TEST(test_array_null_operations, 1);
  RUN_TEST(test_array_non_null_operations, 1);
  RUN_TEST(test_array_zero_operations, 1);
  RUN_TEST(test_array_non_zero_operations, 1);
  RUN_TEST(test_array_positive_operations, 1);
  RUN_TEST(test_array_negative_operations, 1);
  RUN_TEST(test_array_zero_or_positive_operations, 1);
  RUN_TEST(test_array_zero_or_negative_operations, 1);
  RUN_TEST(test_array_odd_operations, 1);
  RUN_TEST(test_array_even_operations, 1);
  RUN_TEST(test_array_prime_operations, 1);
  RUN_TEST(test_array_composite_operations, 1);
  RUN_TEST(test_array_perfect_square_operations, 1);
  RUN_TEST(test_array_perfect_cube_operations, 1);
  RUN_TEST(test_array_fibonacci_operations, 1);
  RUN_TEST(test_array_factorial_operations, 1);
  RUN_TEST(test_array_power_operations, 1);
  RUN_TEST(test_array_logarithm_operations, 1);
  RUN_TEST(test_array_square_root_operations, 1);
  RUN_TEST(test_array_cube_root_operations, 1);
  RUN_TEST(test_array_golden_ratio_operations, 1);
  RUN_TEST(test_array_pi_operations, 1);
  RUN_TEST(test_array_e_operations, 1);

  return (UnityEnd());
}
